# Generated by Django 3.2.8 on 2021-11-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coverimage',
            old_name='cover_image_url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='post',
            name='post_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='delete_time',
            field=models.DateTimeField(),
        ),
    ]
