# Generated by Django 3.2.8 on 2021-11-03 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211103_0730'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='magazine',
            table='magazines',
        ),
    ]
