# Generated by Django 3.2.8 on 2021-11-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_magazine_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_delete',
            new_name='is_delete',
        ),
        migrations.RemoveField(
            model_name='coverimage',
            name='delete_time',
        ),
        migrations.AddField(
            model_name='coverimage',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
