# Generated by Django 3.2.8 on 2021-11-03 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211103_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='delete_time',
        ),
    ]
