# Generated by Django 3.2.9 on 2021-11-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211103_0729'),
        ('posts', '0006_remove_post_delete_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='magazine',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='post_users', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coverimage',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.post'),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.tag'),
        ),
        migrations.DeleteModel(
            name='Magazine',
        ),
    ]
