# Generated by Django 3.2.9 on 2021-11-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20211108_1003'),
        ('users', '0002_auto_20211103_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='like_post',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', through='users.Like', to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.tag'),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
    ]
